branch-defaults:
  master:
    environment: stores-env
global:
  application_name: stores
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.03 v1.3.0 running PHP 5.5
  default_region: ap-northeast-1
  profile: eb-cli
  sc: git
